# Generated by Django 3.1.3 on 2020-11-26 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20201126_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
