# Generated by Django 3.1.3 on 2020-11-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20201126_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='lat',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='lng',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
