# Generated by Django 3.1.3 on 2020-11-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20201126_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceuser',
            name='cnic',
        ),
    ]
