# Generated by Django 3.1.3 on 2020-11-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_remove_attendanceuser_cnic'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='attendanceuser',
            managers=[
            ],
        ),
    ]
