# Generated by Django 3.1.3 on 2020-11-27 10:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20201127_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.date(2020, 11, 27), null=True)),
                ('time', models.TimeField(blank=True, default=datetime.time(10, 15, 3, 961780))),
                ('lat', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('lng', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('ispresent', models.BooleanField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_mst',
                'ordering': ['id'],
            },
        ),
    ]
