# Generated by Django 3.1.3 on 2020-12-11 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_auto_20201205_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception', models.TextField(blank=True, default=None, null=True)),
                ('app_version', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('platform', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('device', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('device_model', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
            options={
                'db_table': 'crash_tb',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 12, 11), null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(5, 5, 55, 634543)),
        ),
    ]
