# Generated by Django 3.1.3 on 2020-12-11 05:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_auto_20201211_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 11, 5, 57, 44, 399975)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='isactive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 11, 5, 57, 51, 528062)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crash',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 11, 5, 58, 0, 264293)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crash',
            name='isactive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='crash',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 11, 5, 58, 4, 904165)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 11, 5, 58, 11, 647748)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='isactive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 11, 5, 58, 15, 336070)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(5, 56, 24, 169306)),
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField(blank=True, default=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('search_params', models.TextField(blank=True, default=None, null=True)),
                ('app_version', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('platform', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('device', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('device_model', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_tb',
                'ordering': ['id'],
            },
        ),
    ]
