# Generated by Django 3.1.3 on 2020-12-11 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_auto_20201211_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceuser',
            name='app_version',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendanceuser',
            name='brand',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendanceuser',
            name='device',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendanceuser',
            name='device_model',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendanceuser',
            name='platform',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(7, 4, 31, 345922)),
        ),
    ]
