# Generated by Django 3.1.3 on 2020-12-11 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_auto_20201211_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(9, 33, 12, 115354)),
        ),
    ]
